# channel can be freely selected
# id: youtube.com/channel/{id}
# num: number of videos to download

channels = [
			{"channel": "3Blue1Brown", "id": "UCYO_jab_esuFRV4b17AJtAw", "num": 3},
			{"channel": "5 Ideen", "id": "UCXTTZIvh1UAlf0kv6XHvOtg", "num": 1},
			{"channel": "100 Sekunden Physik", "id": "UCEJDM_70A2EiRqZ41l6bZlg", "num": 2},
			{"channel": "Aktien mit Kopf", "id": "UCpV9LpCg4uwYCQZ3qoEn_YQ", "num": 3},
			{"channel": "Ali Nadem", "id": "UCz6S3Ll5gKs5Mmy79SlRVlA", "num": 3},
			{"channel": "Andrew Kirby", "id": "UC8JNIm02zw8h_3NBrP_zsZA", "num": 5},
			{"channel": "ASAP Science", "id": "UCC552Sd-3nyi_tk2BudLUzA", "num": 2},
			{"channel": "Average Linux User", "id": "UCZiL6BoryLWxyapUuVYW27g", "num": 3},
			{"channel": "AVI ", "id": "UCQBmHPn9xj44J0LUBRAv5Uw", "num": 2},
			{"channel": "Bisqwit", "id": "UCKTehwyGCKF-b2wo0RKwrcg", "num": 2},
			{"channel": "blackpenredpen", "id": "UC_SvYP0k05UKiJ_2ndB02IA", "num": 7},
			{"channel": "Brotcrunsher", "id": "UC-3thK6H2pfxxGAa7qljipQ", "num": 4},
			{"channel": "Cg Kid", "id": "UCacn-Cy4KtIm-dl0iuLHAUA", "num": 3},
			{"channel": "Charles Krueger", "id": "UCSLnD8xd-81Lc96OE9kBkOQ", "num": 3},
			{"channel": "Computerphile", "id": "UC9-y-6csu5WGm29I7JiwpnA", "num": 2},
			{"channel": "CS Dojo", "id": "UCxX9wt5FWQUAAz4UrysqK9A", "num": 2},
			{"channel": "dakotawind", "id": "UC--70ql_IxJmhmqXqrkJrWQ", "num": 2},
			{"channel": "Deutscher Hanfverband", "id": "UCNJxn7JS4saCHPsnD91yf9Q", "num": 3},
			{"channel": "Domain of Science", "id": "UCxqAWLTk1CmBvZFPzeZMd9A", "num": 2},
			{"channel": "DREW", "id": "UCjie-6rgFLkYsNVGvWG12xg", "num": 2},
			{"channel": "Drug Education Agency", "id": "UCFmLi6X1mojkFZOFngNR9tQ", "num": 2},
			{"channel": "Eddie Woo", "id": "UCq0EGvLTyy-LLT1oUSO_0FQ", "num": 5},
			{"channel": "Engineering Explained", "id": "UClqhvGmHcvWL9w3R48t9QXQ", "num": 2},
			{"channel": "Flammable Maths", "id": "UCtAIs1VCQrymlAnw3mGonhw", "num": 5},
			{"channel": "Fratm", "id": "UCfXpCALnoC2zsdcKx2XirbQ", "num": 2},
			{"channel": "Gedanken tanken", "id": "UC2AnkjPy95aL0X-q9MPm2-Q", "num": 3},
			{"channel": "Giz Edwards", "id": "UC1u5y6G9doAZYt5zztcn6JA", "num": 4},
			{"channel": "Green Rabbit", "id": "UCbLBFACJUmyDSaouN9ucnnA", "num": 4},
			{"channel": "Hello World", "id": "UCFZ-TZHiOgTg-BPbJDgI7zw", "num": 2},
			{"channel": "Horst Lüning", "id": "UC5i6nCpwmDVKo98sZD2AAcQ", "num": 2},
			{"channel": "How to beast", "id": "UCtQEjfEFzba37ozoXK40r3w", "num": 2},
			{"channel": "howtolucid.com", "id": "UCYTEnIQJ2tpYyK0AKBUal-A", "num": 2},
			{"channel": "huMAN", "id": "UCT2dUsMtd08RfaH12O9DCDg", "num": 2},
			{"channel": "Hyperraum", "id": "UCrT3IAsBHwc9DB2HPO-9S6Q", "num": 2},
			{"channel": "JP Performance", "id": "UC1-VOKyTJrgLiBeiJqzeIUQ", "num": 4},
			{"channel": "Kanzlei WBS", "id": "UCb5TfGtSgvNPVPQawfCFuAw", "num": 4},
			{"channel": "Koi Fresco", "id": "UCFJZQtrh5Ksncayy2FaoNbQ", "num": 2},
			{"channel": "Kolja investiert", "id": "UCM_VUg9JdtfKKPBVyxqrgcQ", "num": 2},
			{"channel": "KreativeVein", "id": "UC_rnVAawdzhcnWePdFJRRng", "num": 2},
			{"channel": "Kurzgesagt", "id": "UCsXVk37bltHxD1rDPwtNM8Q", "num": 2},
			{"channel": "LAHWF", "id": "UCQlVOYJyQp64rA12ac0mv6g", "num": 2},
			{"channel": "Level1Techs", "id": "UC4w1YQAJMWOz4qtxinq55LQ", "num": 2},
			{"channel": "LiveOverflow", "id": "UClcE-kVhqyiHCcjYwcpfj9w", "num": 2},
			{"channel": "Luke Smith", "id": "UC2eYFnH61tmytImy1mTYvhA", "num": 4},
			{"channel": "Malte Helmhold", "id": "UCtLLr2p5ZsKTppwE9ctVO5A", "num": 2},
			{"channel": "Mathologer", "id": "UC1_uAIS3r8Vu6JjXWvastJg", "num": 2},
			{"channel": "Mic the vegan", "id": "UCGJq0eQZoFSwgcqgxIE9MHw", "num": 2},
			{"channel": "mikkois", "id": "UC9459CRFjiCq52yKuiraD4w", "num": 2},
			{"channel": "Numberphile", "id": "UCoxcjq-8xIDTYp3uz647V5A", "num": 2},
			{"channel": "Oliver Flesch", "id": "UCYo2MjFS5C7Wynyty9wTM7g", "num": 2},
			{"channel": "OPEN MIND", "id": "UCEtYtMoD26j2BJBJ4w_hM6w", "num": 2},
			{"channel": "PBS Infinite Series", "id": "UCs4aHmggTfFrpkPcWSaBN9g", "num": 2},
			{"channel": "Peter Frahm", "id": "UCwV0CAC1UW1FMGo8-Pc1azw", "num": 2},
			{"channel": "Project Alpha", "id": "UCzoZaQca_SB0wxK-iSI_16Q", "num": 2},
			{"channel": "PsychedSubstance", "id": "UCn8V3KNSgDr1Dai77_y8JrQ", "num": 2},
			{"channel": "psychologie-lernen.de", "id": "UCKqYM6Qzx-0IVReMjiX8fTg", "num": 2},
			{"channel": "RAW Spirituality", "id": "UCDlC2yGOv2RfN5W9moPZN1Q", "num": 2},
			{"channel": "Redefabrik", "id": "UCkC-9P-VbzSNzsgMwtGdOXg", "num": 2},
			{"channel": "School of hard nugs", "id": "UCmSd4S-CjoZ-AfYx_0BDwUA", "num": 2},
			{"channel": "Sempervideo", "id": "UCCI6C8hD-hTZi2JEmS7zvQw", "num": 2},
			{"channel": "Simon Clark", "id": "UCRRr_xrOm66qaigIbwFLvbQ", "num": 2},
			{"channel": "SpaceTimeBadass", "id": "UCjdrE-MgL2mEYWPihLouGEA", "num": 2},
			{"channel": "Steuern mit Kopf", "id": "UCCwCa-faBqcY-zJ4PS1lCHA", "num": 2},
			{"channel": "Stuermer Cannabis Show", "id": "UCeIwvWBEjURqOc1C0GgtBxw", "num": 2},
			{"channel": "SWIM", "id": "UCOWGNAei4hIjOna_JgWGCOA", "num": 2},
			{"channel": "TechGumbo", "id": "UCaSM4GqhbaVmRT7fmmFmR1w", "num": 2},
			{"channel": "TED", "id": "UCAuUUnT6oDeKwE6v1NGQxug", "num": 4},
			{"channel": "The Charisma Matrix", "id": "UCs14Smim-bliHN4GBEom-Vg", "num": 2},
			{"channel": "The Drug Classroom", "id": "UCmnRJ-G1Qq2kdOzIe5fBBaQ", "num": 2},
			{"channel": "The Lazy Engineer", "id": "UCMox2m1RbHiVe7abWNSueEQ", "num": 2},
			{"channel": "Tilo Jung", "id": "UCv1WDP5EiipMQ__C4Cg6aow", "num": 2},
			{"channel": "tomatolix", "id": "UCNCktfoFAXtXnMlhjyc9SPA", "num": 2},
			{"channel": "tutorialLinux", "id": "UCvA_wgsX6eFAOXI8Rbg_WiQ", "num": 3},
			{"channel": "unicks.eu", "id": "UCnZIn_CYjz0ErPs1ktH-2lQ", "num": 3},
			{"channel": "Urknall, Weltall & das Leben", "id": "UClDnGiwSyTyu7gxO8X5U18g", "num": 2},
			{"channel": "Valentin Möller", "id": "UCyHK70XuRaWjwBnz2jHWxeg", "num": 2},
			{"channel": "Versicherungen mit Kopf", "id": "UC70-qPE5cS_aOYAOGnM_24g", "num": 2},
			{"channel": "We Plants Are Happy Plants", "id": "UCXLdDPcQD0BWjb00fGdFFYg", "num": 2},
			{"channel": "Weitz/ HAW Hamburg", "id": "UCjTfChr0yyz4iZq0x12Q6xA", "num": 5},
			{"channel": "What I've Learned", "id": "UCqYPhGiB9tkShZorfgcL2lA", "num": 2},
			{"channel": "Word Porn", "id": "UCbiS-tMYNTIUv1y6uVh27Zw", "num": 2},
			{"channel": "Your Mate Tom", "id": "UCXSF1F_RFRUVNXX4QmB6vmw", "num": 2}]